### ISSUE TITLE
different location for jaxb-api-2.3.1.jar

### ISSUE THREAD

**Issue by moderski** [jacekkow/pzsigner-deb#1]
When following instructions from README.md I have encountered the following error during "debuild -us -uc" step:
wget -N --progress=dot:mega "http://central.maven.org/maven2/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar"
--2020-02-06 14:53:57--  http://central.maven.org/maven2/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar
Resolving central.maven.org (central.maven.org)... failed: Name or service not known.
wget: unable to resolve host address ‘central.maven.org’

It seems that the file is no longer available at the given location. I have found the new location for the file (it also applies to the jaxb-impl) which can be hardcoded into debian/rules as:
wget -N --progress=dot:mega "https://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar"
wget -N --progress=dot:mega "https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.3.3-b01/jaxb-impl-2.3.3-b01.jar"

**Comment by jacekkow** [comment]
Maven central have switched to HTTPS, hence the issue.
I have updated the repo and pushed new version here:
https://github.com/jacekkow/pzsigner-deb/releases/download/v1.0-3/pzsigner_1.0-3_amd64.deb
